controller:
  ingressController:
    image:
      tag: "3.1"
    env:
      feature_gates: "FillIDs=true"
    konnect:
      license:
        enabled: true
      enabled: true
      runtimeGroupID: "24dcf0ca-3d0f-4503-ad77-d0f44e2375f0"
      tlsClientSecretName: konnect-client-tls
      apiHostname: "us.kic.api.konghq.com"

gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.5"
  env:
    konnect_mode: "on"
    vitals: "off"
    cluster_mtls: pki
    cluster_telemetry_endpoint: "02fd5d36cc.us.tp0.konghq.com:443"
    cluster_telemetry_server_name: "02fd5d36cc.us.tp0.konghq.com"
    cluster_cert: /etc/secrets/konnect-client-tls/tls.crt
    cluster_cert_key: /etc/secrets/konnect-client-tls/tls.key
    lua_ssl_trusted_certificate: system

  secretVolumes:
    - konnect-client-tls