apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: proxy-ssl
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: kong
