apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt
  namespace: kong
plugin: jwt
config:
  uri_param_names: ["jwt"]
  cookie_names: ["jwt"]
  claims_to_verify: ["exp"]
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: jwt-consumer
  namespace: kong
username: jwt-user
custom_id: jwt-user-id
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: kong
type: Opaque
data:
  key: bXktdW5pcXVlLWp3dC1rZXk=
  secret: bFJ6T1hFcWI3ODZ1OHRVSW5lQUMxN25NeGFKbmd1Wml1N2JFcU9Rc3RyOD0=